focus_cross_monitor=1
new_is_master=1
view_current_to_back=1
sync_obj_enable=1

# imports
source=./extra.conf
source=./startup.conf
source=./keybind.conf
source=./mouse.conf
source=./layout.conf
source=./visual.conf
source=./window.conf
