# Audio / brightness
bind=NONE,XF86AudioRaiseVolume,spawn_shell,wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn_shell,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn_shell,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=NONE,XF86AudioMicMute,spawn_shell,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# catalyst-shell
bind=SUPER,space,spawn,catalyst-launcher
bind=SUPER+SHIFT,c,spawn,catalyst-dashboard
bind=SUPER+SHIFT,v,spawn,catalyst-clipboard
bind=SUPER,l,spawn,catalyst-lock
binds=SUPER,a,spawn,true

bind=SUPER,q,killclient
bind=SUPER+CTRL,q,spawn,xkill
bind=SUPER+SHIFT,q,quit
bind=SUPER+SHIFT,r,reload_config

# Windows
bind=SUPER,Tab,focusstack,next
bind=SUPER+SHIFT,Tab,focusstack,prev
bind=SUPER,x,toggleoverview
bind=SUPER,f,togglefullscreen
bind=SUPER,w,togglefloating

# Focus
bind=SUPER,v,focusdir,left
bind=SUPER,b,focusdir,down
bind=SUPER,n,focusdir,up
bind=SUPER,m,focusdir,right

# Swap windows
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

# Swap with master area
bind=SUPER+ALT,Return,zoom

# Cycle windows in the stack
bind=SUPER,apostrophe,focusstack,next
bind=SUPER+SHIFT,apostrophe,focusstack,prev

# Keyboard layout (Alt+Caps)
bind=ALT,Caps_Lock,switch_keyboard_layout

# Layouts
bind=SUPER,j,switch_layout
bind=SUPER+CTRL,f,setlayout,fair
bind=SUPER+CTRL,t,setlayout,tile
bind=SUPER+CTRL,m,setlayout,monocle

# Tile split ratio
bind=SUPER+CTRL,0,setmfact,1.5
bind=SUPER,minus,setmfact,-0.05
bind=SUPER,equal,setmfact,+0.05

# Tags
bind=SUPER,Left,tagtoleft
bind=SUPER,Right,tagtoright
axisbind=SUPER,LEFT,tagtoleft
axisbind=SUPER,RIGHT,tagtoright

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

# Monitors
bind=SUPER+CTRL,h,tagmon,left
bind=SUPER+CTRL,j,tagmon,down
bind=SUPER+CTRL,k,tagmon,up
bind=SUPER+CTRL,l,tagmon,right

# Apps
bind=SUPER+SHIFT,f,spawn,thunar
bind=SUPER,t,spawn,ghostty

# Screenshot
bind=SUPER+SHIFT,s,spawn,catalyst-screenshot
bind=NONE,Print,spawn,catalyst-screenshot
bind=SUPER+SHIFT,x,spawn,catalyst-screenshot-save
bind=SUPER+SHIFT,z,spawn,catalyst-markup
bind=SUPER+SHIFT,p,spawn,catalyst-colorpicker
