# gaps
gappih=0
gappiv=0
gappoh=0
gappov=0

# borders
borderpx=0
dropcolor=0x00000000

# blur
blur=1
blur_layer=1
blur_optimized=0
blur_params_num_passes=4
blur_params_radius=8
# drag tile
drag_tile_small=0

# misc
xwayland_persistence=1
smartgaps=1
