no_border_when_single=1

window_rule=tags:2,app_id:^(vesktop|Vesktop)$
window_rule=tags:2,app_id:org.telegram.desktop
window_rule=tags:3,app_id:com.obsproject.Studio

window_rule=is_floating:1,app_id:pavucontrol
window_rule=is_floating:1,title:qs-markup
window_rule=is_floating:1,title:.*[Pp]icture.in.[Pp]icture.*
window_rule=is_floating:1,title:.*pop-up.*
window_rule=is_floating:1,title:.*task_dialog.*

layer_rule=no_animation:1,no_blur:1,layer_name:selection
layer_rule=no_animation:1,no_blur:1,layer_name:^quickshell.* fullscreen + tearing
window_rule=is_fullscreen:1,ignore_maximize:1,app_id:^steam_app_
window_rule=force_tearing:1,app_id:^steam_app_
window_rule=idle_inhibit_when_focus:1,app_id:^steam_app_
