no_border_when_single=1

windowrule=tags:2,appid:^(vesktop|Vesktop)$
windowrule=tags:2,appid:org.telegram.desktop
windowrule=tags:3,appid:com.obsproject.Studio

windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,title:qs-markup
windowrule=isfloating:1,title:.*[Pp]icture.in.[Pp]icture.*
windowrule=isfloating:1,title:.*pop-up.*
windowrule=isfloating:1,title:.*task_dialog.*

layerrule=noanim:1,noblur:1,layer_name:selection
layerrule=noanim:1,noblur:1,layer_name:^quickshell.* fullscreen + tearing
windowrule=isfullscreen:1,ignore_maximize:1,appid:^steam_app_
windowrule=force_tearing:1,appid:^steam_app_
windowrule=idleinhibit_when_focus:1,appid:^steam_app_
